### ISSUE TITLE
Y.ImageCropper in Bootstrap 3

### ISSUE THREAD

**Issue by lifeart** [liferay/alloy-ui#80]
For an Image inside Bootstrap modal window ImageCropper controls now working (all controls in one spot: left-top angle of image), if image parent has css {"text-align":center}, then cropper has a problem with Zero coordinates of his background image. + z-index error. 

aui-image-cropper, V 3.0.0

**Comment by lifeart** [comment]
example: http://codepen.io/lifeart/pen/mympwG

**Comment by lifeart** [comment]
if image has styled max-width or max-height, and image bigger then (max-width or max-height), cropper has a Zoom problems.

**Comment by mairatma** [comment]
Thanks a lot for reporting these problems. I've opened two separate jira issues for those (https://issues.liferay.com/browse/AUI-1837 and https://issues.liferay.com/browse/AUI-1838).

Next time, keep in mind that issues should be posted on Jira instead of GitHub :)
https://github.com/liferay/alloy-ui/blob/master/CONTRIBUTING.md#1-issues

I'll close this since we'll be working on the jira issues instead then. You should be able to access them too if you wish to see the progress or add something.
