### ISSUE TITLE
I need to create a custom view for the aui scheduler

### ISSUE THREAD

**Issue by fatihtastemur** [liferay/alloy-ui#89]
General information for the website: Resource view required - if possible
Kind of development: Customization of existing website
Description of requirements/features: I would like to use the alloy-ui component for my applications scheduling needs, however rather than displaying a week view, I would like to view separate resources in the columns.

As an example, this sort of view : http://www.bryntum.com/examples/scheduler-latest/examples/vertical-orientation/vertical.html

But using this component : http://alloyui.com/examples/scheduler/

Is this in fact possible even? I would need to respond to all the events there are currently with the component, so I can detect event drag/drop etc.

**Comment by mairatma** [comment]
I don't believe there's a way to do this out of the box, but AlloyUI's scheduler allows you to implement your own views and use them, so you could try implementing a new view for it. The only requirement is that it has to extend from `SchedulerDayView`, so you should take a look at it and see if extending it or one of the other existing views (like `SchedulerWeekView`, which is the one in the example you showed) can be enough for your purposes. Since the columns won't be dates I'm not sure how easy it will be though.
