### ISSUE TITLE
Scheduler is showing events on the wrong month

### ISSUE THREAD

**Issue by filiperinaldi** [liferay/alloy-ui#94]
As stated by the issue title, the the scheduler is not showing the events on the correct month. It always shows on the following month. The issue can be seen from the example page:
http://alloyui.com/examples/scheduler

The demo has an event on the 4th January 2013, but the calendar is showing it on February.

**Comment by filiperinaldi** [comment]
I just realised you are using Jira now.

**Comment by mairatma** [comment]
It's true, we're using Jira now, but since this is simple to answer I'll take the change and explain here.

The component is not wrong actually, nor is the demo. The date being passed to the component is in February, not in January. The javascript **Date** object uses zero indexed numbers for month codes, so January is 0 and February is 1, even though it looks weird. To confirm, just type on your browser's console: `new Date(2013, 1, 4, 5).toString()`. This will output something like: **Mon Feb 04 2013 05:00:00 GMT-0300 (BRT)**.
